= Ka-Ro flavoured NXP i.MX BSP release

This is the BSP manifest repository for the Ka-Ro flavoured version of NXP's
i.MX8M Mini Yocto BSP. (rev. L4.14.78_1.0.0_ga 2019-01-17 - as can be found
link:https://source.codeaurora.org/external/imx/imx-manifest[here @ CodeAurora])

This primarly encompasses the inclusion of changes to make it compatible with
the Ka-Ro TX8M-1610, which is Ka-Ro's i.MX8M Mini solution.


== Downloading

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

For version 1.25, the checksum for `repo` is:
`SHA-256 d06f33115aea44e583c8669375b35aad397176a411de3461897444d247b6c220`

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir fsl-bsp-karo-tx8m
$: cd fsl-bsp-karo-tx8m
$: repo init --no-clone-bundle -u https://github.com/karo-electronics/karo-bsp -b imx-linux-sumo
$: repo sync --no-clone-bundle

NOTE: That `fsl-bsp-karo-tx8m` is a directory name for the BSP that can be
freely chosen by the user.

NOTE: Not all repositories used herein support the "clone-bundle" feature and
therefore the option ("`--no-clone-bundle`") is strongly recommended when
using the `repo` tool.

At the end of the commands you have every metadata you need to start work
with.


== Pre-Building info

=== Distro

Hereafter is a list of `DISTRO` configurations.

> Note that DirectFB is no longer supported, and fsl-imx-wayland and fsl-imx-fb
> are not supported on i.MX 8.
> 
> - `fsl-imx-x11`      - X11 graphics are not supported on i.MX 8.
> - `fsl-imx-wayland`  - Wayland weston graphics.
> - `fsl-imx-xwayland` - Wayland graphics and X11. X11 applications using EGL are
>                        not supported.
> - `fsl-imx-fb`       - Frame Buffer graphics - no X11 or Wayland.
>                        Frame Buffer is not supported on i.MX 8.


NOTE: `DISTRO=<distro configuration name>` is the distro, which configures the
build environment and it is stored in `meta-fsl-bsp-release/imx/meta-sdk/conf/distro`.


=== Machine

A list of supported `MACHINE` configurations:

- `tx8m-1610`

NOTE: The full list of supported `MACHINE` configuration also includes NXP
solutions, which aren't listed here, it being a Ka-Ro flavoured BSP.


=== Images

> Following a a list of images that can be build: +
>  +
> - `core-image-minimal` +
> - `core-image-base` +
> - `core-image-sato` +
> - `fsl-image-machine-test` +
> - `fsl-image-validation-imx` +
> - `fsl-image-qt5-validation-imx` +
> - `fsl-image-multimedia` +
> - `fsl-image-multimedia-full` +


> Some image recipes:
> 
> `fsl-image-gui` - full image with demos and tests used for testing with graphics, no QT. +
> `fsl-image-qt5` - fsl-image-gui with QT 5.9.

These image recipes can be build via the `$: bitbake` command:

[source,console]
$: bitbake <image-recipes>

=== Reference

Above information can also be found and as indicated by quote are partly of
NXP's documentation accompanying their i.MX8M Mini Yocto BSP, e.g.:

i.MX Yocto Project User's Guide, Rev. L4.14.78-1.0.0_ga, 01/2019


== Building

To start a image build choose one of the `DISTRO` and the appropriate
`MACHINE` and then setup the build environment and directory in which to
compile the Yocto BSP.

To *intially* setup the build environment and directory one will need to use
the `fsl-setup-release.sh`.


[source,console]
$: MACHINE=tx8m-1610 DISTRO=fsl-imx-wayland source fsl-setup-release.sh -b a-sensible-build-dir-name-of-choice
$: bitbake core-image-minimal


Where `core-image-minimal` is one of the above named image recipes [[Images]]
that the user can choose from.

NOTE: Not all image recipes might build and that breaks might occur, to quote
from NXP documentation:

> Note if the poky community distro is used then build breaks will happen with
> some components using our `meta-fsl-bsp-release` layer.


=== Re-Use a previous `<build-dir>`

Repeated build runs, after e.g. the initial terminal has been closed, can be
initiated as followed:

[source,console]
$: source ./setup-environment <previously-used-build-dir-name>
$: bitbake core-image-minimal

The projects and recipes source code are checked out at
`<fsl-bsp-karo-tx8m>/sources`.

Each branch will have detailed READMEs describing exact syntax.


== Contributing

To contribute to and patches specific to the Ka-Ro should be sent for review
to <yocto-devel@karo-electronics.de>, or throw it into github's issues system,
provided here:

https://github.com/karo-electronics/karo-nxp-bsp/issues


For commit/patch message guidelines, please refer to:

https://openembedded.org/wiki/Commit_Patch_Message_Guidelines


=== Mailing list:

Ka-Ro has no mailing list, to contribute sent patches specific
for review to <yocto-devel@karo-electronics.de>.


=== Creating Patches

When creating patches of the last commit, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='karo-nxp-bsp][PATCH][imx-linux-sumo' -1

When sending patches, please use something like:

[source,console]
$: git send-email --to yocto-devel@karo-electronics.de <generated patch>


---
https://www.karo-electronics.de[Ka-Ro electronics GmbH]

Contact support: support@karo-electronics.de
