@Library('yocto-lib@2026.06.1') _

def machineFamilies = getFamilies('nxp')
def machineOptions = machineFamilies.collectMany { family -> getMachines(family) }
def distroOptions = getDistros()

properties([
    parameters([
        [
            $class: 'ChoiceParameter',
            name: 'MACHINES',
            description: 'Select one or more machines. Or nothing for all.',
            choiceType: 'PT_CHECKBOX',
            filterable: true,
            script: [
                $class: 'GroovyScript',
                script: [
                    sandbox: true,
                    script: "return ${machineOptions.inspect()}"
                ]
            ]
        ],
        [
            $class: 'ChoiceParameter',
            name: 'DISTROS',
            description: 'Select one or more distros. Or nothing for all.',
            choiceType: 'PT_CHECKBOX',
            filterable: true,
            script: [
                $class: 'GroovyScript',
                script: [
                    sandbox: true,
                    script: "return ${distroOptions.inspect()}"
                ]
            ]
        ],
        choice(
            name: 'MODE',
            choices: ['BUILD', 'BUILD + TEST', 'TEST'],
            description: 'Choose mode'
        ),
        booleanParam(
            name: 'BUILD_FEATURES',
            defaultValue: false,
            description: 'Build distro features'
        ),
        booleanParam(
            name: 'CREATE_RELEASE',
            defaultValue: false,
            description: 'Create and publish release'
        )
    ])
])

pipeline {
    agent any

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '20'))
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
        skipStagesAfterUnstable()
    }

    environment {
        GIT_URL = "${scm.userRemoteConfigs[0].url}"
        BRANCH_NAME =  "${env.TAG_NAME ? 'refs/tags/' + env.TAG_NAME : env.BRANCH_NAME}"
    }

    stages {
        stage('Checkout') {      
            when {
                expression { return params.MODE.contains('BUILD') }
            }

            steps {
                deleteDir()

                checkoutYocto(
                    env.GIT_URL,
                    env.BRANCH_NAME
                )
            }
        }

        stage('Build Combinations') {
            matrix {
                axes {
                    axis {
                        name 'MACHINE'
                        values 'qs8m-mq00', 'qs8m-nd00', 'qs91-3110', 'qs93-5210',
                               'qsxm-mm60', 'qsxp-ml81', 'tx8m-1610', 'tx8m-1620',
                               'tx8m-nd00', 'tx8p-ml81', 'tx91-3110', 'tx93-5210'
                    }
                }

                when {
                    expression {
                        def selected = (params.MACHINES ?: '')
                            .split(',')
                            .collect { it.trim() }
                            .findAll { it }

                        return selected.isEmpty() || selected.contains(env.MACHINE)
                    }
                }

                stages {
                    stage('Build') {
                        steps {
                            build job: "yocto-build-machine",
                                parameters: [
                                    string(name: 'WORKSPACE', value: env.WORKSPACE),
                                    string(name: 'MACHINE', value: env.MACHINE),
                                    string(name: 'DISTROS', value: env.DISTROS),
                                    string(name: 'MODE', value: params.MODE),
                                    booleanParam(name: 'BUILD_FEATURES', value: params.BUILD_FEATURES)
                                ],
                                wait: true,
                                propagate: true
                        }
                    }
                }
            }
        }

        stage('Create Release') {
            when {
                allOf {
                    expression { return params.CREATE_RELEASE }
                    expression { return params.MODE.contains('BUILD') }
                    expression { return params.DISTROS.isEmpty() || (
                        params.DISTROS.contains('karo-minimal') &&
                        params.DISTROS.contains('karo-wayland')
                    ) }
                    expression { return env.GIT_URL.contains('github') }
                    expression { return env.TAG_NAME ==~ /^KARO-\d{4}-\d{2}-\d{2}$/ }
                }
            }

            matrix {
                axes {
                    axis {
                        name 'FAMILY'
                        values 'qs8m', 'qsxm', 'qsxp', 'qs91', 'qs93', 'tx8m', 'tx8p', 'tx91', 'tx93'
                    }
                }

                when {
                    expression {
                        def selected = (params.MACHINES ?: '')
                            .split(',')
                            .collect { it.trim() }
                            .findAll { it }

                        return selected.isEmpty() || selected.containsAll(getMachines(env.FAMILY))
                    }
                }

                stages {
                    stage('Publish') {
                        steps {
                            createRelease(env.FAMILY, env.TAG_NAME)
                        }
                    }
                }
            }
        }
    }
}